In [2]:
import torch
x = torch.tensor([[1, 2], [3, 4], [5, 6]])    # shape: (3, 2), dim: 2
y = torch.tensor([[7,8], [9, 10], [11, 12]])

# **1. stack**  

지정한 dim 인자에 차원을 한 개 추가하여 cat 하는 것과 같음

**예1. dim=0 결합**  
기존 `x.shape=(3, 2)`의 첫 번째 차원(dim=0)에 차원 추가를 해준다.  
그러면 `x'.shape=(1, 3, 2)`가 되며 y도 마찬가지로 `y'.shape(1, 3, 2)`가 된다.  
x'와 y'를 결합하면 `shape=(2, 3, 2)`가 된다.  
굉장히 단순하다.

In [3]:
z = torch.stack([x, y], dim=0)
print(z.shape); print(z)

torch.Size([2, 3, 2])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])


In [4]:
z = torch.stack([x, y], dim=1)
print(z.shape); print(z)

torch.Size([3, 2, 2])
tensor([[[ 1,  2],
         [ 7,  8]],

        [[ 3,  4],
         [ 9, 10]],

        [[ 5,  6],
         [11, 12]]])


In [5]:
z = torch.stack([x, y], dim=2)
print(z.shape); print(z)

torch.Size([3, 2, 2])
tensor([[[ 1,  7],
         [ 2,  8]],

        [[ 3,  9],
         [ 4, 10]],

        [[ 5, 11],
         [ 6, 12]]])


# **2. cat**  

차원 추가 없이 해당 dim 차원의 원소 간 결합

In [6]:
z = torch.cat([x, y], dim=0)
print(z.shape); print(z)

torch.Size([6, 2])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


In [7]:
z = torch.cat([x, y], dim=0)
print(z.shape); print(z)

torch.Size([6, 2])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


# **3. cat으로 stack 구현하기**

텐서에 차원을 추가하여 cat 수행

In [9]:
dim = 0     # 결합할 차원

x2 = x.unsqueeze(dim)   # stack 처럼 차원 추가 
y2 = y.unsqueeze(dim)

z = torch.cat([x2, y2], dim=0)
print(z.shape); print(z)

torch.Size([2, 3, 2])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])


stack과 비교

In [11]:
z = torch.stack([x, y], dim=0)
print(z.shape); print(z)

torch.Size([2, 3, 2])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])
